# Generated by Django 4.0.4 on 2022-05-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
